### ISSUE TITLE
Dispatch Issues

### ISSUE THREAD

**Issue by zylava** [UCLA-CS130/Team-OO-BUN-2#5]
Hi,

I am on the team that's supposed to work on the reverse proxy handler of your team. I noticed that something is wrong with your dispatch mechanism. 
Say if the config file is as following:
path / StaticHandler {
  root static;
}
path /echo EchoHandler {
}

Server.cpp will first call EchoHandler, and then it will call StaticHandler as well. This is incorrect, because for this class, we are doing longest prefix first. It poses a lot of problems when I try to have to servers with one being the proxy of the other, because the static one could get called.

I am wondering if one of you could fix this soon.

Thank you!

**Comment by ss-jiang** [comment]
Hello,

I'm assuming that the part of the code you are referring to are the if statements, specifically the 
`else if (statement->tokens_[i]=="path" && statement->tokens_[i+1]=="/echo")` and 
`else if (statement->tokens_[i]=="path")` is that correct?

**Comment by ss-jiang** [comment]
I think I figured out the issue you were having. 
Previously, we checked if the tokens were "/echo" or "/" instead of checking for which handler name was parsed by the config parser. I updated our server.cpp so that creating handlers is reliant only on the handler name now, so I think the issue should be fixed. 

Let me know if the issue is still here!
@zylava

**Comment by zylava** [comment]
Thanks for fixing the issue!
